[disable_list]
waifus = [
    "Bambietta Basterbine",
    "Giselle Gewelle",
    "Candice Catnipp",
    "Liltotto Lamperd",
    "Meninas McAllon",
    "Shinku",
    "Suigintou",
    "Hinaichigo",
    "Kanaria (RM)",
    "Suiseiseki",
    "Souseiseki",
    "Kirakishou",
    "Barasuishou",
    "Lilisen",
    "Makima",
    "Kurumi Tokisaki",
    "Mirko",
    "Junko Enoshima"
]
